sudo: required

services:
  - docker

before_install:
  - docker build -t pedroluiznogueira/kardbank:"$VERSION" -f Dockerfile.dev .

script:
  - docker run -e CI=true pedroluiznogueira/kardbank npm run test -- --watch=false --coverage --passWithNoTests

after_success:
  - docker build -t pedroluiznogueira/kardbank:"$VERSION" .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push pedroluiznogueira/kardbank && docker push pedroluiznogueira/kardbank:"$VERSION"